// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Tue, 28 Feb 2017 12:48:56 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.0.20528.0")]
[assembly: AssemblyFileVersion("1.0.20528.1248")]